# Assignment

Import numpy as np

In [3]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [4]:
l=[1,2,3,4,5]
arr1=np.array(l)
arr1

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [6]:
arr2=np.arange(1,10).reshape(3,3)
arr2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [8]:
arr3=np.arange(1,18,2).reshape(3,3)
arr3

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [36]:
l=[]
for i in range(10):
    l.append(np.random.rand()*10)
arr4=np.array(l)
arr4

array([5.37452799, 1.24760785, 9.82267014, 4.9981108 , 0.57889439,
       2.62615738, 8.91219324, 5.38217791, 0.61872725, 1.78769109])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [18]:
arr5=np.array([1,2,3,4,5]).reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [20]:
arr5.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [22]:
arr6=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr6[2])
print(arr6[3])
print(arr6[8])


3
4
9


Print alternate elements of that array

In [26]:
arr6[1:10:2]

array([ 2,  4,  6,  8, 10])

Change last 3 elements into 100 using broadcasting and print

In [27]:
arr6[7:]=100
arr6

array([  1,   2,   3,   4,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [32]:
arr7=np.arange(1,26).reshape(5,5)
arr7[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])